---
title: "R Notebook"
output: html_notebook
---

```{r, message = FALSE}
library(dplyr)
library(magrittr)
library(quantmod)
library(RcppRoll)
library(readr)
library(tseries)
library(PerformanceAnalytics)
```



```{r, message=FALSE}
#brent <- read_csv("Data/Brent_daily_spot.csv")
wti <- read_csv("Data/WTI_daily_spot.csv")
#load("wti_project.Rda")
```

```{r}
# create xts object
wti.xts <- xts(wti$wti, as.Date(wti$day, format='%m/%d/%y'))

#filter with these dates:
#start.date = as.POSIXct("1998-01-01")
#end.date = as.POSIXct("2015-01-01")

# By using an index that is the logical AND of two vectors
#wti.xts <- wti.xts[paste(start.date,end.date,sep="::")]
```

```{r}
#first return calc
#wti.return <- wti.xts %>% log() %>% diff(lag = 1) #%>% exp() %>% subtract(1)

#return cited in Modelling oil price volatility (Narayana and Narayana)
return.calc <- function(series){
  return.series <- series
  
  len <- length(series)
  
  for(i in 1:(len-1)){
    return.iter <- (series[[i+1]] - series[[i]]) / series[[i]]
    return.series[[i+1]] <- return.iter
  }
  
  return.series[[1]] <- NA
  
  return(return.series)
}

wti.return <- return.calc(wti.xts)

```



```{r}
# calculate returns

# create ts object
wti.ts <- zoo(wti$wti, order.by=as.Date(as.character(wti$day), format='%m/%d/%y')) %>%
  as.ts() %>%
  na.remove()

wti.xts <- wti.xts[-1]
wti.return <- wti.return[-1]
```


```{r}
vols.30 <- apply(wti.return , 2, function(x) {
    #use rolling 30 day window to calculate standard deviation.
    #annualize by multiplying by square root of time
  wti.return %>% runSD(n=30)
})

#vols.30 <- rollapply(wti.ts, 30, sd)
```

```{r}
vols.5 <- apply(wti.return, 2, function(x) {
    #use rolling 5 day window to calculate standard deviation.
    #annualize by multiplying by square root of time
  wti.return %>% runSD(n=5)
})

#vols.5 <- rollapply(wti.ts, 5, sd)
```

```{r}
len <- length(wti.xts)
wti.combined <- cbind.xts(wti.xts, wti.return, vols.30, vols.5) %>% na.omit()
colnames(wti.combined)<- c("close", "return", "30-day", "5-day")
```


Take absolute value of returns
```{r}
wti.combined$return <- abs(wti.combined$return)
wti.df <- as.data.frame(wti.combined)
```

```{r}
save(wti, wti.return, wti.xts, wti.ts, wti.combined, wti.df, file = "wti_project.Rda")
save(wti, wti.return, wti.xts, wti.ts, wti.combined, wti.df, file = "Manuscript/wti_project.Rda")
save(wti, wti.return, wti.xts, wti.ts, wti.combined, wti.df, file = "ShinyApp/OilVolatility/wti_project.Rda")

```