---
title: "Variance comparison"
author: "J. Hamski"
date: "4/20/2017"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(changepoint)
library(zoo)
library(tseries)
library(dplyr)
library(ggplot2)
library(knitr)

load("wti_project.Rda")
```


```{r}
cpt.1 = cpt.mean(wti.ts, method="PELT", penalty = "Manual", pen.value = 10000, minseglen = 250)

#cpt.1 = cpt.mean(wti.ts, method="PELT", penalty = "SIC", minseglen = 250)

#length(cpt.1@cpts)
plot(cpt.1, cpt.width = 4)
```

```{r}
regimes <- cpt.1@cpts
regime.index <- NULL

for (i in 1:length(regimes)){
  ifelse(i == 1, 
         regime.index.iter <- rep.int(i, times = length(1:regimes[i])), 
         regime.index.iter <- rep.int(i, times = length((regimes[i-1]+1):regimes[i])))
  regime.index <- c(regime.index, regime.index.iter)
}

wti.regimes <- cbind(wti.ts, regime.index) %>% as.data.frame()
colnames(wti.regimes) <- c("close", "regime")
wti.regimes$regime <- as.factor(wti.regimes$regime)
```

```{r}
price.regime.descriptive <- wti.regimes %>%
  group_by(regime) %>% 
  summarize(med = median(close), var = var(close))

plot(x = price.regime.descriptive$med, y = price.regime.descriptive$var, type = "p")
summary(lm(var ~ med, data = price.regime.descriptive))
kable(price.regime.descriptive)
```

```{r}
ggplot(wti.regimes, aes(sample = close)) + stat_qq() + facet_grid(regime ~ .)
ggplot(wti.regimes, aes(x = regime, y = close)) + geom_violin(draw_quantiles = 0.5) #+ geom_boxplot() 
```

https://en.wikipedia.org/wiki/F-test_of_equality_of_variances

```{r}

wti.regimes.ret <-  cbind(wti.regimes[31:nrow(wti.regimes),], wti.df$return) 
colnames(wti.regimes.ret) <- c("close", "regime", "returns")

barlets.test.price <- bartlett.test(x = wti.regimes$close, g = wti.regimes$regime)
barlets.test.price

barlets.test.return <- bartlett.test(x = wti.regimes.ret$returns, g = wti.regimes.ret$regime, na.action =  na.omit)
barlets.test.return
```
The Fligner Killeen test is a non-parametric test for homogeneity of group variances. This test indicates that the variances are indeed different scross the 9 regimes. 

```{r}
fligner.test(x = wti.regimes$close, g = wti.regimes$regime)

fligner.test(x = wti.regimes.ret$returns, g = wti.regimes.ret$regime, na.action =  na.omit)
```

```{r}
ggplot(wti.regimes.ret, aes(sample = returns)) + stat_qq() + facet_grid(regime ~ .)
ggplot(wti.regimes.ret, aes(x = regime, y = returns)) + geom_violin(draw_quantiles = 0.5) #+ geom_boxplot() 
```


